# preset leaderboard for the app to fallback to if the current leaderboard file is not found
preset_leaderboard = {
                    "Capitol Cities": {
                        10: [
                            ("Bob", 2175),
                            ("Sarah", 2000),
                            ("anonymous", 1750),
                            ("Jake", 1500),
                            ("Bill", 1250),
                            ("Kate", 1000),
                            ("countryfan", 750),
                            ("gazza", 500),
                            ("Duck", 250),
                            ("anonymous", 150)
                        ],
                        11: [
                            ("Bob", 2400),
                            ("Sarah", 2150),
                            ("anonymous", 1900),
                            ("Jake", 1650),
                            ("Bill", 1400),
                            ("Kate", 1150),
                            ("countryfan", 900),
                            ("gazza", 650),
                            ("Duck", 400),
                            ("anonymous", 300)
                        ],
                        12: [
                            ("Bob", 2500),
                            ("Sarah", 2350),
                            ("anonymous", 2100),
                            ("Jake", 1850),
                            ("Bill", 1550),
                            ("Kate", 1300),
                            ("countryfan", 1050),
                            ("gazza", 800),
                            ("Duck", 550),
                            ("anonymous", 400)
                        ],
                        13: [
                            ("Bob", 2550),
                            ("Sarah", 2300),
                            ("anonymous", 2150),
                            ("Jake", 1900),
                            ("Bill", 1650),
                            ("Kate", 1400),
                            ("countryfan", 1250),
                            ("gazza", 900),
                            ("Duck", 650),
                            ("anonymous", 400)
                        ],
                        14: [
                            ("Bob", 2650),
                            ("Sarah", 2350),
                            ("anonymous", 2250),
                            ("Jake", 1950),
                            ("Bill", 1750),
                            ("Kate", 1450),
                            ("countryfan", 1300),
                            ("gazza", 950),
                            ("Duck", 650),
                            ("anonymous", 450)
                        ],
                        15: [
                            ("Bob", 2850),
                            ("Sarah", 2450),
                            ("anonymous", 2250),
                            ("Jake", 2000),
                            ("Bill", 1850),
                            ("Kate", 1550),
                            ("countryfan", 1350),
                            ("gazza", 1050),
                            ("Duck", 750),
                            ("anonymous", 500)
                        ],
                        16: [
                            ("Bob", 3000),
                            ("Sarah", 2650),
                            ("anonymous", 2350),
                            ("Jake", 2100),
                            ("Bill", 1900),
                            ("Kate", 1650),
                            ("countryfan", 1400),
                            ("gazza", 1200),
                            ("Duck", 900),
                            ("anonymous", 650)
                        ],
                        17: [
                            ("Bob", 3150),
                            ("Sarah", 2750),
                            ("anonymous", 2400),
                            ("Jake", 2250),
                            ("Bill", 2000),
                            ("Kate", 1850),
                            ("countryfan", 1550),
                            ("gazza", 1300),
                            ("Duck", 950),
                            ("anonymous", 750)
                        ],
                        18: [
                            ("Bob", 3350),
                            ("Sarah", 2900),
                            ("anonymous", 2600),
                            ("Jake", 2350),
                            ("Bill", 2100),
                            ("Kate", 1900),
                            ("countryfan", 1700),
                            ("gazza", 1500),
                            ("Duck", 1200),
                            ("anonymous", 900)
                        ],
                        19: [
                            ("Bob", 3500),
                            ("Sarah", 3200),
                            ("anonymous", 2800),
                            ("Jake", 2500),
                            ("Bill", 2250),
                            ("Kate", 2000),
                            ("countryfan", 1850),
                            ("gazza", 1600),
                            ("Duck", 1250),
                            ("anonymous", 1000)
                        ],
                        20: [
                            ("Bob", 4000),
                            ("Sarah", 3500),
                            ("anonymous", 3000),
                            ("Jake", 2750),
                            ("Bill", 2500),
                            ("Kate", 2250),
                            ("countryfan", 2000),
                            ("gazza", 1750),
                            ("Duck", 1500),
                            ("anonymous", 1250)
                        ]
                    },
                    "World Geography": {
                        10: [
                            ("Bob", 2175),
                            ("Sarah", 2000),
                            ("anonymous", 1750),
                            ("Jake", 1500),
                            ("Bill", 1250),
                            ("Kate", 1000),
                            ("countryfan", 750),
                            ("gazza", 500),
                            ("Duck", 250),
                            ("anonymous", 150)
                        ],
                        11: [
                            ("Bob", 2400),
                            ("Sarah", 2150),
                            ("anonymous", 1900),
                            ("Jake", 1650),
                            ("Bill", 1400),
                            ("Kate", 1150),
                            ("countryfan", 900),
                            ("gazza", 650),
                            ("Duck", 400),
                            ("anonymous", 300)
                        ],
                        12: [
                            ("Bob", 2500),
                            ("Sarah", 2350),
                            ("anonymous", 2100),
                            ("Jake", 1850),
                            ("Bill", 1550),
                            ("Kate", 1300),
                            ("countryfan", 1050),
                            ("gazza", 800),
                            ("Duck", 550),
                            ("anonymous", 400)
                        ],
                        13: [
                            ("Bob", 2550),
                            ("Sarah", 2300),
                            ("anonymous", 2150),
                            ("Jake", 1900),
                            ("Bill", 1650),
                            ("Kate", 1400),
                            ("countryfan", 1250),
                            ("gazza", 900),
                            ("Duck", 650),
                            ("anonymous", 400)
                        ],
                        14: [
                            ("Bob", 2650),
                            ("Sarah", 2350),
                            ("anonymous", 2250),
                            ("Jake", 1950),
                            ("Bill", 1750),
                            ("Kate", 1450),
                            ("countryfan", 1300),
                            ("gazza", 950),
                            ("Duck", 650),
                            ("anonymous", 450)
                        ],
                        15: [
                            ("Bob", 2850),
                            ("Sarah", 2450),
                            ("anonymous", 2250),
                            ("Jake", 2000),
                            ("Bill", 1850),
                            ("Kate", 1550),
                            ("countryfan", 1350),
                            ("gazza", 1050),
                            ("Duck", 750),
                            ("anonymous", 500)
                        ],
                        16: [
                            ("Bob", 3000),
                            ("Sarah", 2650),
                            ("anonymous", 2350),
                            ("Jake", 2100),
                            ("Bill", 1900),
                            ("Kate", 1650),
                            ("countryfan", 1400),
                            ("gazza", 1200),
                            ("Duck", 900),
                            ("anonymous", 650)
                        ],
                        17: [
                            ("Bob", 3150),
                            ("Sarah", 2750),
                            ("anonymous", 2400),
                            ("Jake", 2250),
                            ("Bill", 2000),
                            ("Kate", 1850),
                            ("countryfan", 1550),
                            ("gazza", 1300),
                            ("Duck", 950),
                            ("anonymous", 750)
                        ],
                        18: [
                            ("Bob", 3350),
                            ("Sarah", 2900),
                            ("anonymous", 2600),
                            ("Jake", 2350),
                            ("Bill", 2100),
                            ("Kate", 1900),
                            ("countryfan", 1700),
                            ("gazza", 1500),
                            ("Duck", 1200),
                            ("anonymous", 900)
                        ],
                        19: [
                            ("Bob", 3500),
                            ("Sarah", 3200),
                            ("anonymous", 2800),
                            ("Jake", 2500),
                            ("Bill", 2250),
                            ("Kate", 2000),
                            ("countryfan", 1850),
                            ("gazza", 1600),
                            ("Duck", 1250),
                            ("anonymous", 1000)
                        ],
                        20: [
                            ("Bob", 4000),
                            ("Sarah", 3500),
                            ("anonymous", 3000),
                            ("Jake", 2750),
                            ("Bill", 2500),
                            ("Kate", 2250),
                            ("countryfan", 2000),
                            ("gazza", 1750),
                            ("Duck", 1500),
                            ("anonymous", 1250)
                        ]
                    },
                    "World Languages": {
                        10: [
                            ("Bob", 2175),
                            ("Sarah", 2000),
                            ("anonymous", 1750),
                            ("Jake", 1500),
                            ("Bill", 1250),
                            ("Kate", 1000),
                            ("countryfan", 750),
                            ("gazza", 500),
                            ("Duck", 250),
                            ("anonymous", 150)
                        ],
                        11: [
                            ("Bob", 2400),
                            ("Sarah", 2150),
                            ("anonymous", 1900),
                            ("Jake", 1650),
                            ("Bill", 1400),
                            ("Kate", 1150),
                            ("countryfan", 900),
                            ("gazza", 650),
                            ("Duck", 400),
                            ("anonymous", 300)
                        ],
                        12: [
                            ("Bob", 2500),
                            ("Sarah", 2350),
                            ("anonymous", 2100),
                            ("Jake", 1850),
                            ("Bill", 1550),
                            ("Kate", 1300),
                            ("countryfan", 1050),
                            ("gazza", 800),
                            ("Duck", 550),
                            ("anonymous", 400)
                        ],
                        13: [
                            ("Bob", 2550),
                            ("Sarah", 2300),
                            ("anonymous", 2150),
                            ("Jake", 1900),
                            ("Bill", 1650),
                            ("Kate", 1400),
                            ("countryfan", 1250),
                            ("gazza", 900),
                            ("Duck", 650),
                            ("anonymous", 400)
                        ],
                        14: [
                            ("Bob", 2650),
                            ("Sarah", 2350),
                            ("anonymous", 2250),
                            ("Jake", 1950),
                            ("Bill", 1750),
                            ("Kate", 1450),
                            ("countryfan", 1300),
                            ("gazza", 950),
                            ("Duck", 650),
                            ("anonymous", 450)
                        ],
                        15: [
                            ("Bob", 2850),
                            ("Sarah", 2450),
                            ("anonymous", 2250),
                            ("Jake", 2000),
                            ("Bill", 1850),
                            ("Kate", 1550),
                            ("countryfan", 1350),
                            ("gazza", 1050),
                            ("Duck", 750),
                            ("anonymous", 500)
                        ],
                        16: [
                            ("Bob", 3000),
                            ("Sarah", 2650),
                            ("anonymous", 2350),
                            ("Jake", 2100),
                            ("Bill", 1900),
                            ("Kate", 1650),
                            ("countryfan", 1400),
                            ("gazza", 1200),
                            ("Duck", 900),
                            ("anonymous", 650)
                        ],
                        17: [
                            ("Bob", 3150),
                            ("Sarah", 2750),
                            ("anonymous", 2400),
                            ("Jake", 2250),
                            ("Bill", 2000),
                            ("Kate", 1850),
                            ("countryfan", 1550),
                            ("gazza", 1300),
                            ("Duck", 950),
                            ("anonymous", 750)
                        ],
                        18: [
                            ("Bob", 3350),
                            ("Sarah", 2900),
                            ("anonymous", 2600),
                            ("Jake", 2350),
                            ("Bill", 2100),
                            ("Kate", 1900),
                            ("countryfan", 1700),
                            ("gazza", 1500),
                            ("Duck", 1200),
                            ("anonymous", 900)
                        ],
                        19: [
                            ("Bob", 3500),
                            ("Sarah", 3200),
                            ("anonymous", 2800),
                            ("Jake", 2500),
                            ("Bill", 2250),
                            ("Kate", 2000),
                            ("countryfan", 1850),
                            ("gazza", 1600),
                            ("Duck", 1250),
                            ("anonymous", 1000)
                        ],
                        20: [
                            ("Bob", 4000),
                            ("Sarah", 3500),
                            ("anonymous", 3000),
                            ("Jake", 2750),
                            ("Bill", 2500),
                            ("Kate", 2250),
                            ("countryfan", 2000),
                            ("gazza", 1750),
                            ("Duck", 1500),
                            ("anonymous", 1250)
                        ]
                    }
}
